insert into Delivery_Man (id, name, Status) values (1, 'Hogan', 'en cour');
insert into Delivery_Man (id, name, Status) values (2, 'Eduard', 'en cour');
insert into Delivery_Man (id, name, Status) values (3, 'Issie', 'en cour');
insert into Delivery_Man (id, name, Status) values (4, 'Sephira', 'en cour');
insert into Delivery_Man (id, name, Status) values (5, 'Garnet', 'pause');
insert into Delivery_Man (id, name, Status) values (6, 'Flory', 'finish');
insert into Delivery_Man (id, name, Status) values (7, 'Yale', 'pause');
insert into Delivery_Man (id, name, Status) values (8, 'Jeremias', 'finish');
insert into Delivery_Man (id, name, Status) values (9, 'Daniella', 'pause');
insert into Delivery_Man (id, name, Status) values (10, 'Benjamen', 'en cour');
insert into Delivery_Man (id, name, Status) values (11, 'Adiana', 'finish');
insert into Delivery_Man (id, name, Status) values (12, 'Stesha', 'pause');
insert into Delivery_Man (id, name, Status) values (13, 'Merrily', 'en cour');
insert into Delivery_Man (id, name, Status) values (14, 'Stormie', 'en cour');
insert into Delivery_Man (id, name, Status) values (15, 'Meggie', 'finish');
insert into Delivery_Man (id, name, Status) values (16, 'Broderic', 'en cour');
insert into Delivery_Man (id, name, Status) values (17, 'Raymund', 'finish');
insert into Delivery_Man (id, name, Status) values (18, 'Dalston', 'en cour');
insert into Delivery_Man (id, name, Status) values (19, 'Rudie', 'pause');
insert into Delivery_Man (id, name, Status) values (20, 'Joelie', 'finish');
insert into Delivery_Man (id, name, Status) values (21, 'Nyssa', 'en cour');
insert into Delivery_Man (id, name, Status) values (22, 'Jerrine', 'pause');
insert into Delivery_Man (id, name, Status) values (23, 'Natal', 'finish');
insert into Delivery_Man (id, name, Status) values (24, 'Hollie', 'en cour');
insert into Delivery_Man (id, name, Status) values (25, 'Gaspard', 'pause');
insert into Delivery_Man (id, name, Status) values (26, 'Dillon', 'en cour');
insert into Delivery_Man (id, name, Status) values (27, 'Claudell', 'pause');
insert into Delivery_Man (id, name, Status) values (28, 'Salomon', 'pause');
insert into Delivery_Man (id, name, Status) values (29, 'Mathias', 'finish');
insert into Delivery_Man (id, name, Status) values (30, 'Maggee', 'en cour');
insert into Delivery_Man (id, name, Status) values (31, 'Aretha', 'en cour');
insert into Delivery_Man (id, name, Status) values (32, 'Calv', 'en cour');
insert into Delivery_Man (id, name, Status) values (33, 'De witt', 'finish');
insert into Delivery_Man (id, name, Status) values (34, 'Sandye', 'pause');
insert into Delivery_Man (id, name, Status) values (35, 'Ara', 'finish');
insert into Delivery_Man (id, name, Status) values (36, 'Aigneis', 'en cour');
insert into Delivery_Man (id, name, Status) values (37, 'Danette', 'en cour');
insert into Delivery_Man (id, name, Status) values (38, 'Rhett', 'pause');
insert into Delivery_Man (id, name, Status) values (39, 'Annelise', 'finish');
insert into Delivery_Man (id, name, Status) values (40, 'Merna', 'pause');
insert into Delivery_Man (id, name, Status) values (41, 'Gnni', 'en cour');
insert into Delivery_Man (id, name, Status) values (42, 'Allayne', 'finish');
insert into Delivery_Man (id, name, Status) values (43, 'Warde', 'pause');
insert into Delivery_Man (id, name, Status) values (44, 'Orton', 'finish');
insert into Delivery_Man (id, name, Status) values (45, 'Gill', 'finish');
insert into Delivery_Man (id, name, Status) values (46, 'Estrellita', 'en cour');
insert into Delivery_Man (id, name, Status) values (47, 'Artie', 'pause');
insert into Delivery_Man (id, name, Status) values (48, 'Aland', 'pause');
insert into Delivery_Man (id, name, Status) values (49, 'Madonna', 'pause');
insert into Delivery_Man (id, name, Status) values (50, 'Fran', 'en cour');
insert into Delivery_Man (id, name, Status) values (51, 'Marlena', 'pause');
insert into Delivery_Man (id, name, Status) values (52, 'Rosalind', 'finish');
insert into Delivery_Man (id, name, Status) values (53, 'Dania', 'en cour');
insert into Delivery_Man (id, name, Status) values (54, 'Zebulon', 'en cour');
insert into Delivery_Man (id, name, Status) values (55, 'Kathy', 'pause');
insert into Delivery_Man (id, name, Status) values (56, 'Kristofer', 'finish');
insert into Delivery_Man (id, name, Status) values (57, 'Witty', 'pause');
insert into Delivery_Man (id, name, Status) values (58, 'Aldo', 'en cour');
insert into Delivery_Man (id, name, Status) values (59, 'Dominique', 'pause');
insert into Delivery_Man (id, name, Status) values (60, 'Arnuad', 'finish');
insert into Delivery_Man (id, name, Status) values (61, 'Eleanora', 'finish');
insert into Delivery_Man (id, name, Status) values (62, 'Scarlet', 'finish');
insert into Delivery_Man (id, name, Status) values (63, 'Slade', 'pause');
insert into Delivery_Man (id, name, Status) values (64, 'Jens', 'finish');
insert into Delivery_Man (id, name, Status) values (65, 'Tedman', 'pause');
insert into Delivery_Man (id, name, Status) values (66, 'Ursola', 'en cour');
insert into Delivery_Man (id, name, Status) values (67, 'Felecia', 'en cour');
insert into Delivery_Man (id, name, Status) values (68, 'Ileane', 'en cour');
insert into Delivery_Man (id, name, Status) values (69, 'Jeth', 'finish');
insert into Delivery_Man (id, name, Status) values (70, 'Gaelan', 'pause');
insert into Delivery_Man (id, name, Status) values (71, 'Riannon', 'finish');
insert into Delivery_Man (id, name, Status) values (72, 'Essie', 'finish');
insert into Delivery_Man (id, name, Status) values (73, 'Wally', 'en cour');
insert into Delivery_Man (id, name, Status) values (74, 'Lily', 'pause');
insert into Delivery_Man (id, name, Status) values (75, 'Brandyn', 'finish');
insert into Delivery_Man (id, name, Status) values (76, 'Gretchen', 'pause');
insert into Delivery_Man (id, name, Status) values (77, 'Brigit', 'finish');
insert into Delivery_Man (id, name, Status) values (78, 'Lyon', 'pause');
insert into Delivery_Man (id, name, Status) values (79, 'Heath', 'en cour');
insert into Delivery_Man (id, name, Status) values (80, 'Arly', 'finish');
insert into Delivery_Man (id, name, Status) values (81, 'Somerset', 'pause');
insert into Delivery_Man (id, name, Status) values (82, 'Nike', 'finish');
insert into Delivery_Man (id, name, Status) values (83, 'Ollie', 'finish');
insert into Delivery_Man (id, name, Status) values (84, 'Mickey', 'pause');
insert into Delivery_Man (id, name, Status) values (85, 'Marley', 'pause');
insert into Delivery_Man (id, name, Status) values (86, 'Jess', 'en cour');
insert into Delivery_Man (id, name, Status) values (87, 'Kalil', 'finish');
insert into Delivery_Man (id, name, Status) values (88, 'Maighdiln', 'finish');
insert into Delivery_Man (id, name, Status) values (89, 'Barnabas', 'finish');
insert into Delivery_Man (id, name, Status) values (90, 'Renee', 'pause');
insert into Delivery_Man (id, name, Status) values (91, 'Aundrea', 'finish');
insert into Delivery_Man (id, name, Status) values (92, 'Lezlie', 'pause');
insert into Delivery_Man (id, name, Status) values (93, 'Gonzales', 'finish');
insert into Delivery_Man (id, name, Status) values (94, 'Howey', 'en cour');
insert into Delivery_Man (id, name, Status) values (95, 'Oneida', 'en cour');
insert into Delivery_Man (id, name, Status) values (96, 'Winni', 'en cour');
insert into Delivery_Man (id, name, Status) values (97, 'Sheila', 'pause');
insert into Delivery_Man (id, name, Status) values (98, 'Arlana', 'en cour');
insert into Delivery_Man (id, name, Status) values (99, 'Justus', 'en cour');
insert into Delivery_Man (id, name, Status) values (100, 'Patrice', 'pause');
insert into Delivery_Man (id, name, Status) values (101, 'Jenine', 'finish');
insert into Delivery_Man (id, name, Status) values (102, 'Claudina', 'en cour');
insert into Delivery_Man (id, name, Status) values (103, 'Glen', 'finish');
insert into Delivery_Man (id, name, Status) values (104, 'Jard', 'finish');
insert into Delivery_Man (id, name, Status) values (105, 'Clevie', 'finish');
insert into Delivery_Man (id, name, Status) values (106, 'Nadeen', 'en cour');
insert into Delivery_Man (id, name, Status) values (107, 'Arturo', 'en cour');
insert into Delivery_Man (id, name, Status) values (108, 'Sheila-kathryn', 'en cour');
insert into Delivery_Man (id, name, Status) values (109, 'Blaine', 'finish');
insert into Delivery_Man (id, name, Status) values (110, 'Lauraine', 'finish');
insert into Delivery_Man (id, name, Status) values (111, 'Carmina', 'pause');
insert into Delivery_Man (id, name, Status) values (112, 'Beatrisa', 'finish');
insert into Delivery_Man (id, name, Status) values (113, 'Ricca', 'pause');
insert into Delivery_Man (id, name, Status) values (114, 'Sullivan', 'en cour');
insert into Delivery_Man (id, name, Status) values (115, 'Eal', 'en cour');
insert into Delivery_Man (id, name, Status) values (116, 'Revkah', 'pause');
insert into Delivery_Man (id, name, Status) values (117, 'Way', 'finish');
insert into Delivery_Man (id, name, Status) values (118, 'Nana', 'pause');
insert into Delivery_Man (id, name, Status) values (119, 'Wenda', 'finish');
insert into Delivery_Man (id, name, Status) values (120, 'Dunn', 'pause');
insert into Delivery_Man (id, name, Status) values (121, 'Ki', 'pause');
insert into Delivery_Man (id, name, Status) values (122, 'Pauletta', 'pause');
insert into Delivery_Man (id, name, Status) values (123, 'Valerye', 'en cour');
insert into Delivery_Man (id, name, Status) values (124, 'Odella', 'finish');
insert into Delivery_Man (id, name, Status) values (125, 'Desi', 'finish');
insert into Delivery_Man (id, name, Status) values (126, 'Bren', 'finish');
insert into Delivery_Man (id, name, Status) values (127, 'Windham', 'pause');
insert into Delivery_Man (id, name, Status) values (128, 'Candie', 'en cour');
insert into Delivery_Man (id, name, Status) values (129, 'Daveen', 'en cour');
insert into Delivery_Man (id, name, Status) values (130, 'Brina', 'pause');
insert into Delivery_Man (id, name, Status) values (131, 'Warren', 'en cour');
insert into Delivery_Man (id, name, Status) values (132, 'Ibrahim', 'finish');
insert into Delivery_Man (id, name, Status) values (133, 'Bondie', 'finish');
insert into Delivery_Man (id, name, Status) values (134, 'Halette', 'pause');
insert into Delivery_Man (id, name, Status) values (135, 'Gianni', 'finish');
insert into Delivery_Man (id, name, Status) values (136, 'Harald', 'finish');
insert into Delivery_Man (id, name, Status) values (137, 'Gregorio', 'finish');
insert into Delivery_Man (id, name, Status) values (138, 'Georgette', 'en cour');
insert into Delivery_Man (id, name, Status) values (139, 'Saba', 'pause');
insert into Delivery_Man (id, name, Status) values (140, 'Maxim', 'en cour');
insert into Delivery_Man (id, name, Status) values (141, 'Sky', 'en cour');
insert into Delivery_Man (id, name, Status) values (142, 'Rosalind', 'finish');
insert into Delivery_Man (id, name, Status) values (143, 'Cece', 'finish');
insert into Delivery_Man (id, name, Status) values (144, 'Emlynn', 'en cour');
insert into Delivery_Man (id, name, Status) values (145, 'Laureen', 'en cour');
insert into Delivery_Man (id, name, Status) values (146, 'Jonathan', 'en cour');
insert into Delivery_Man (id, name, Status) values (147, 'Emmalynn', 'finish');
insert into Delivery_Man (id, name, Status) values (148, 'Bebe', 'finish');
insert into Delivery_Man (id, name, Status) values (149, 'Michael', 'en cour');
insert into Delivery_Man (id, name, Status) values (150, 'Prescott', 'finish');
insert into Delivery_Man (id, name, Status) values (151, 'Fidelity', 'en cour');
insert into Delivery_Man (id, name, Status) values (152, 'Tate', 'finish');
insert into Delivery_Man (id, name, Status) values (153, 'Irina', 'pause');
insert into Delivery_Man (id, name, Status) values (154, 'Adah', 'pause');
insert into Delivery_Man (id, name, Status) values (155, 'Giff', 'finish');
insert into Delivery_Man (id, name, Status) values (156, 'Lamont', 'en cour');
insert into Delivery_Man (id, name, Status) values (157, 'Sherlocke', 'en cour');
insert into Delivery_Man (id, name, Status) values (158, 'Leoine', 'en cour');
insert into Delivery_Man (id, name, Status) values (159, 'Marieann', 'pause');
insert into Delivery_Man (id, name, Status) values (160, 'Malinda', 'pause');
insert into Delivery_Man (id, name, Status) values (161, 'Lotti', 'pause');
insert into Delivery_Man (id, name, Status) values (162, 'Katha', 'finish');
insert into Delivery_Man (id, name, Status) values (163, 'Mirabelle', 'en cour');
insert into Delivery_Man (id, name, Status) values (164, 'Dewitt', 'finish');
insert into Delivery_Man (id, name, Status) values (165, 'Hoebart', 'en cour');
insert into Delivery_Man (id, name, Status) values (166, 'Scarface', 'pause');
insert into Delivery_Man (id, name, Status) values (167, 'Josephine', 'finish');
insert into Delivery_Man (id, name, Status) values (168, 'Elysia', 'pause');
insert into Delivery_Man (id, name, Status) values (169, 'Giustino', 'en cour');
insert into Delivery_Man (id, name, Status) values (170, 'Kliment', 'en cour');
insert into Delivery_Man (id, name, Status) values (171, 'Zarah', 'pause');
insert into Delivery_Man (id, name, Status) values (172, 'Rebekkah', 'en cour');
insert into Delivery_Man (id, name, Status) values (173, 'Gretchen', 'en cour');
insert into Delivery_Man (id, name, Status) values (174, 'Bell', 'en cour');
insert into Delivery_Man (id, name, Status) values (175, 'Brear', 'pause');
insert into Delivery_Man (id, name, Status) values (176, 'Corabelle', 'en cour');
insert into Delivery_Man (id, name, Status) values (177, 'Gunilla', 'finish');
insert into Delivery_Man (id, name, Status) values (178, 'Corny', 'finish');
insert into Delivery_Man (id, name, Status) values (179, 'August', 'finish');
insert into Delivery_Man (id, name, Status) values (180, 'Virgie', 'pause');
insert into Delivery_Man (id, name, Status) values (181, 'Carlynne', 'en cour');
insert into Delivery_Man (id, name, Status) values (182, 'Loreen', 'pause');
insert into Delivery_Man (id, name, Status) values (183, 'Terri', 'en cour');
insert into Delivery_Man (id, name, Status) values (184, 'Rick', 'pause');
insert into Delivery_Man (id, name, Status) values (185, 'Helena', 'pause');
insert into Delivery_Man (id, name, Status) values (186, 'Rosalia', 'finish');
insert into Delivery_Man (id, name, Status) values (187, 'Westleigh', 'pause');
insert into Delivery_Man (id, name, Status) values (188, 'Linn', 'en cour');
insert into Delivery_Man (id, name, Status) values (189, 'Regan', 'pause');
insert into Delivery_Man (id, name, Status) values (190, 'Gertruda', 'pause');
insert into Delivery_Man (id, name, Status) values (191, 'Wanids', 'finish');
insert into Delivery_Man (id, name, Status) values (192, 'Mick', 'finish');
insert into Delivery_Man (id, name, Status) values (193, 'Roslyn', 'finish');
insert into Delivery_Man (id, name, Status) values (194, 'Francklin', 'en cour');
insert into Delivery_Man (id, name, Status) values (195, 'Davy', 'finish');
insert into Delivery_Man (id, name, Status) values (196, 'Tannie', 'pause');
insert into Delivery_Man (id, name, Status) values (197, 'Marisa', 'en cour');
insert into Delivery_Man (id, name, Status) values (198, 'Kristina', 'en cour');
insert into Delivery_Man (id, name, Status) values (199, 'Vinnie', 'finish');
insert into Delivery_Man (id, name, Status) values (200, 'Oona', 'pause');
insert into Delivery_Man (id, name, Status) values (201, 'Michal', 'finish');
insert into Delivery_Man (id, name, Status) values (202, 'Orin', 'pause');
insert into Delivery_Man (id, name, Status) values (203, 'Paddy', 'en cour');
insert into Delivery_Man (id, name, Status) values (204, 'Skip', 'finish');
insert into Delivery_Man (id, name, Status) values (205, 'Dianna', 'pause');
insert into Delivery_Man (id, name, Status) values (206, 'Jobie', 'pause');
insert into Delivery_Man (id, name, Status) values (207, 'Fanchette', 'en cour');
insert into Delivery_Man (id, name, Status) values (208, 'Kynthia', 'en cour');
insert into Delivery_Man (id, name, Status) values (209, 'Duane', 'en cour');
insert into Delivery_Man (id, name, Status) values (210, 'Ron', 'finish');
insert into Delivery_Man (id, name, Status) values (211, 'Christophe', 'finish');
insert into Delivery_Man (id, name, Status) values (212, 'Geoffry', 'en cour');
insert into Delivery_Man (id, name, Status) values (213, 'Andonis', 'pause');
insert into Delivery_Man (id, name, Status) values (214, 'Mariam', 'finish');
insert into Delivery_Man (id, name, Status) values (215, 'Chlo', 'finish');
insert into Delivery_Man (id, name, Status) values (216, 'Vic', 'en cour');
insert into Delivery_Man (id, name, Status) values (217, 'Diane-marie', 'finish');
insert into Delivery_Man (id, name, Status) values (218, 'Griff', 'en cour');
insert into Delivery_Man (id, name, Status) values (219, 'Chrystal', 'en cour');
insert into Delivery_Man (id, name, Status) values (220, 'Marin', 'pause');
insert into Delivery_Man (id, name, Status) values (221, 'Kassia', 'pause');
insert into Delivery_Man (id, name, Status) values (222, 'Elysia', 'pause');
insert into Delivery_Man (id, name, Status) values (223, 'Nikolas', 'en cour');
insert into Delivery_Man (id, name, Status) values (224, 'Janot', 'pause');
insert into Delivery_Man (id, name, Status) values (225, 'Karlen', 'finish');
insert into Delivery_Man (id, name, Status) values (226, 'Clarisse', 'pause');
insert into Delivery_Man (id, name, Status) values (227, 'Audi', 'finish');
insert into Delivery_Man (id, name, Status) values (228, 'Bibi', 'pause');
insert into Delivery_Man (id, name, Status) values (229, 'Emma', 'finish');
insert into Delivery_Man (id, name, Status) values (230, 'Joye', 'pause');
insert into Delivery_Man (id, name, Status) values (231, 'Audrey', 'pause');
insert into Delivery_Man (id, name, Status) values (232, 'Tailor', 'en cour');
insert into Delivery_Man (id, name, Status) values (233, 'Lida', 'pause');
insert into Delivery_Man (id, name, Status) values (234, 'Bradley', 'en cour');
insert into Delivery_Man (id, name, Status) values (235, 'Vernon', 'finish');
insert into Delivery_Man (id, name, Status) values (236, 'Rowena', 'en cour');
insert into Delivery_Man (id, name, Status) values (237, 'Bondon', 'finish');
insert into Delivery_Man (id, name, Status) values (238, 'Saudra', 'finish');
insert into Delivery_Man (id, name, Status) values (239, 'Loydie', 'finish');
insert into Delivery_Man (id, name, Status) values (240, 'Zebadiah', 'en cour');
insert into Delivery_Man (id, name, Status) values (241, 'Curtice', 'pause');
insert into Delivery_Man (id, name, Status) values (242, 'Ky', 'finish');
insert into Delivery_Man (id, name, Status) values (243, 'Burk', 'en cour');
insert into Delivery_Man (id, name, Status) values (244, 'Zitella', 'pause');
insert into Delivery_Man (id, name, Status) values (245, 'Montague', 'pause');
insert into Delivery_Man (id, name, Status) values (246, 'Tymon', 'en cour');
insert into Delivery_Man (id, name, Status) values (247, 'Harry', 'en cour');
insert into Delivery_Man (id, name, Status) values (248, 'Christabel', 'finish');
insert into Delivery_Man (id, name, Status) values (249, 'Britteny', 'finish');
insert into Delivery_Man (id, name, Status) values (250, 'Gussie', 'pause');
insert into Delivery_Man (id, name, Status) values (251, 'Britney', 'finish');
insert into Delivery_Man (id, name, Status) values (252, 'Lorenza', 'en cour');
insert into Delivery_Man (id, name, Status) values (253, 'Penni', 'finish');
insert into Delivery_Man (id, name, Status) values (254, 'Adler', 'en cour');
insert into Delivery_Man (id, name, Status) values (255, 'Nonie', 'en cour');
insert into Delivery_Man (id, name, Status) values (256, 'Murdock', 'pause');
insert into Delivery_Man (id, name, Status) values (257, 'Xerxes', 'finish');
insert into Delivery_Man (id, name, Status) values (258, 'Roxi', 'en cour');
insert into Delivery_Man (id, name, Status) values (259, 'Kiley', 'en cour');
insert into Delivery_Man (id, name, Status) values (260, 'Theodoric', 'pause');
insert into Delivery_Man (id, name, Status) values (261, 'Camellia', 'finish');
insert into Delivery_Man (id, name, Status) values (262, 'Rebecka', 'finish');
insert into Delivery_Man (id, name, Status) values (263, 'Lizabeth', 'pause');
insert into Delivery_Man (id, name, Status) values (264, 'Colman', 'pause');
insert into Delivery_Man (id, name, Status) values (265, 'Moll', 'pause');
insert into Delivery_Man (id, name, Status) values (266, 'Ky', 'en cour');
insert into Delivery_Man (id, name, Status) values (267, 'Gale', 'finish');
insert into Delivery_Man (id, name, Status) values (268, 'Keri', 'pause');
insert into Delivery_Man (id, name, Status) values (269, 'Prue', 'en cour');
insert into Delivery_Man (id, name, Status) values (270, 'Rena', 'en cour');
insert into Delivery_Man (id, name, Status) values (271, 'Rosalynd', 'pause');
insert into Delivery_Man (id, name, Status) values (272, 'Joella', 'en cour');
insert into Delivery_Man (id, name, Status) values (273, 'Rutter', 'finish');
insert into Delivery_Man (id, name, Status) values (274, 'Rita', 'en cour');
insert into Delivery_Man (id, name, Status) values (275, 'Sarene', 'en cour');
insert into Delivery_Man (id, name, Status) values (276, 'Jonis', 'en cour');
insert into Delivery_Man (id, name, Status) values (277, 'Berny', 'en cour');
insert into Delivery_Man (id, name, Status) values (278, 'Kamillah', 'en cour');
insert into Delivery_Man (id, name, Status) values (279, 'Olag', 'en cour');
insert into Delivery_Man (id, name, Status) values (280, 'Courtney', 'en cour');
insert into Delivery_Man (id, name, Status) values (281, 'Lida', 'finish');
insert into Delivery_Man (id, name, Status) values (282, 'Abel', 'finish');
insert into Delivery_Man (id, name, Status) values (283, 'Karola', 'finish');
insert into Delivery_Man (id, name, Status) values (284, 'Saleem', 'finish');
insert into Delivery_Man (id, name, Status) values (285, 'Boy', 'pause');
insert into Delivery_Man (id, name, Status) values (286, 'Dale', 'pause');
insert into Delivery_Man (id, name, Status) values (287, 'Philippine', 'en cour');
insert into Delivery_Man (id, name, Status) values (288, 'Erhard', 'pause');
insert into Delivery_Man (id, name, Status) values (289, 'Rahal', 'en cour');
insert into Delivery_Man (id, name, Status) values (290, 'Roseann', 'pause');
insert into Delivery_Man (id, name, Status) values (291, 'Sigmund', 'pause');
insert into Delivery_Man (id, name, Status) values (292, 'Jonell', 'pause');
insert into Delivery_Man (id, name, Status) values (293, 'Kaleb', 'pause');
insert into Delivery_Man (id, name, Status) values (294, 'Dunstan', 'finish');
insert into Delivery_Man (id, name, Status) values (295, 'Gerry', 'finish');
insert into Delivery_Man (id, name, Status) values (296, 'Jenelle', 'pause');
insert into Delivery_Man (id, name, Status) values (297, 'Matthiew', 'pause');
insert into Delivery_Man (id, name, Status) values (298, 'Benoite', 'finish');
insert into Delivery_Man (id, name, Status) values (299, 'Dorey', 'pause');
insert into Delivery_Man (id, name, Status) values (300, 'Fritz', 'pause');
insert into Delivery_Man (id, name, Status) values (301, 'Melodie', 'finish');
insert into Delivery_Man (id, name, Status) values (302, 'Rodolph', 'finish');
insert into Delivery_Man (id, name, Status) values (303, 'Waiter', 'en cour');
insert into Delivery_Man (id, name, Status) values (304, 'Cairistiona', 'pause');
insert into Delivery_Man (id, name, Status) values (305, 'Annamaria', 'pause');
insert into Delivery_Man (id, name, Status) values (306, 'Erma', 'finish');
insert into Delivery_Man (id, name, Status) values (307, 'Fitzgerald', 'pause');
insert into Delivery_Man (id, name, Status) values (308, 'Kelley', 'finish');
insert into Delivery_Man (id, name, Status) values (309, 'Jodi', 'pause');
insert into Delivery_Man (id, name, Status) values (310, 'Rosemarie', 'en cour');
insert into Delivery_Man (id, name, Status) values (311, 'Josselyn', 'en cour');
insert into Delivery_Man (id, name, Status) values (312, 'Dulcea', 'pause');
insert into Delivery_Man (id, name, Status) values (313, 'Izzy', 'en cour');
insert into Delivery_Man (id, name, Status) values (314, 'Tabitha', 'finish');
insert into Delivery_Man (id, name, Status) values (315, 'Flossy', 'pause');
insert into Delivery_Man (id, name, Status) values (316, 'Gennifer', 'pause');
insert into Delivery_Man (id, name, Status) values (317, 'Letisha', 'finish');
insert into Delivery_Man (id, name, Status) values (318, 'Nichole', 'pause');
insert into Delivery_Man (id, name, Status) values (319, 'Hugh', 'en cour');
insert into Delivery_Man (id, name, Status) values (320, 'Quincey', 'finish');
insert into Delivery_Man (id, name, Status) values (321, 'Shepherd', 'en cour');
insert into Delivery_Man (id, name, Status) values (322, 'Chere', 'en cour');
insert into Delivery_Man (id, name, Status) values (323, 'Teddie', 'finish');
insert into Delivery_Man (id, name, Status) values (324, 'Benni', 'en cour');
insert into Delivery_Man (id, name, Status) values (325, 'Glyn', 'en cour');
insert into Delivery_Man (id, name, Status) values (326, 'Worthington', 'en cour');
insert into Delivery_Man (id, name, Status) values (327, 'Emmey', 'pause');
insert into Delivery_Man (id, name, Status) values (328, 'Zsazsa', 'pause');
insert into Delivery_Man (id, name, Status) values (329, 'Jaquelyn', 'finish');
insert into Delivery_Man (id, name, Status) values (330, 'Ddene', 'finish');
insert into Delivery_Man (id, name, Status) values (331, 'Ginni', 'finish');
insert into Delivery_Man (id, name, Status) values (332, 'Fabio', 'en cour');
insert into Delivery_Man (id, name, Status) values (333, 'Anita', 'en cour');
insert into Delivery_Man (id, name, Status) values (334, 'Sallyann', 'en cour');
insert into Delivery_Man (id, name, Status) values (335, 'Joellyn', 'en cour');
insert into Delivery_Man (id, name, Status) values (336, 'Llewellyn', 'finish');
insert into Delivery_Man (id, name, Status) values (337, 'Gustie', 'finish');
insert into Delivery_Man (id, name, Status) values (338, 'Priscilla', 'pause');
insert into Delivery_Man (id, name, Status) values (339, 'Franklin', 'finish');
insert into Delivery_Man (id, name, Status) values (340, 'Junia', 'en cour');
insert into Delivery_Man (id, name, Status) values (341, 'Barron', 'pause');
insert into Delivery_Man (id, name, Status) values (342, 'Kary', 'en cour');
insert into Delivery_Man (id, name, Status) values (343, 'Torrie', 'en cour');
insert into Delivery_Man (id, name, Status) values (344, 'Binky', 'en cour');
insert into Delivery_Man (id, name, Status) values (345, 'Marjory', 'pause');
insert into Delivery_Man (id, name, Status) values (346, 'Caroline', 'en cour');
insert into Delivery_Man (id, name, Status) values (347, 'Estelle', 'finish');
insert into Delivery_Man (id, name, Status) values (348, 'Desirae', 'pause');
insert into Delivery_Man (id, name, Status) values (349, 'Sherill', 'finish');
insert into Delivery_Man (id, name, Status) values (350, 'Suzie', 'en cour');
insert into Delivery_Man (id, name, Status) values (351, 'Starlin', 'pause');
insert into Delivery_Man (id, name, Status) values (352, 'Verina', 'en cour');
insert into Delivery_Man (id, name, Status) values (353, 'Verena', 'en cour');
insert into Delivery_Man (id, name, Status) values (354, 'Janot', 'finish');
insert into Delivery_Man (id, name, Status) values (355, 'Nathalie', 'en cour');
insert into Delivery_Man (id, name, Status) values (356, 'Ezra', 'en cour');
insert into Delivery_Man (id, name, Status) values (357, 'Siffre', 'finish');
insert into Delivery_Man (id, name, Status) values (358, 'Imojean', 'en cour');
insert into Delivery_Man (id, name, Status) values (359, 'Vassili', 'en cour');
insert into Delivery_Man (id, name, Status) values (360, 'Juliette', 'en cour');
insert into Delivery_Man (id, name, Status) values (361, 'Danny', 'finish');
insert into Delivery_Man (id, name, Status) values (362, 'Colver', 'en cour');
insert into Delivery_Man (id, name, Status) values (363, 'Tamiko', 'en cour');
insert into Delivery_Man (id, name, Status) values (364, 'Ive', 'finish');
insert into Delivery_Man (id, name, Status) values (365, 'Win', 'pause');
insert into Delivery_Man (id, name, Status) values (366, 'Trix', 'pause');
insert into Delivery_Man (id, name, Status) values (367, 'Elisabeth', 'finish');
insert into Delivery_Man (id, name, Status) values (368, 'Julianna', 'pause');
insert into Delivery_Man (id, name, Status) values (369, 'Paula', 'finish');
insert into Delivery_Man (id, name, Status) values (370, 'Lucky', 'en cour');
insert into Delivery_Man (id, name, Status) values (371, 'Cross', 'finish');
insert into Delivery_Man (id, name, Status) values (372, 'Enrichetta', 'finish');
insert into Delivery_Man (id, name, Status) values (373, 'Paten', 'finish');
insert into Delivery_Man (id, name, Status) values (374, 'Heloise', 'finish');
insert into Delivery_Man (id, name, Status) values (375, 'Clerkclaude', 'pause');
insert into Delivery_Man (id, name, Status) values (376, 'Ignazio', 'pause');
insert into Delivery_Man (id, name, Status) values (377, 'Brody', 'pause');
insert into Delivery_Man (id, name, Status) values (378, 'Phillie', 'finish');
insert into Delivery_Man (id, name, Status) values (379, 'Elbertine', 'en cour');
insert into Delivery_Man (id, name, Status) values (380, 'Conrado', 'pause');
insert into Delivery_Man (id, name, Status) values (381, 'Bradley', 'finish');
insert into Delivery_Man (id, name, Status) values (382, 'Daron', 'finish');
insert into Delivery_Man (id, name, Status) values (383, 'Sheffie', 'pause');
insert into Delivery_Man (id, name, Status) values (384, 'Trumaine', 'finish');
insert into Delivery_Man (id, name, Status) values (385, 'Kerr', 'en cour');
insert into Delivery_Man (id, name, Status) values (386, 'Ashia', 'pause');
insert into Delivery_Man (id, name, Status) values (387, 'Lucita', 'pause');
insert into Delivery_Man (id, name, Status) values (388, 'Lurlene', 'finish');
insert into Delivery_Man (id, name, Status) values (389, 'Deeyn', 'en cour');
insert into Delivery_Man (id, name, Status) values (390, 'Craggy', 'en cour');
insert into Delivery_Man (id, name, Status) values (391, 'Laura', 'pause');
insert into Delivery_Man (id, name, Status) values (392, 'Fidela', 'finish');
insert into Delivery_Man (id, name, Status) values (393, 'Meara', 'finish');
insert into Delivery_Man (id, name, Status) values (394, 'Sophi', 'finish');
insert into Delivery_Man (id, name, Status) values (395, 'Aurelie', 'pause');
insert into Delivery_Man (id, name, Status) values (396, 'Shalna', 'pause');
insert into Delivery_Man (id, name, Status) values (397, 'Witty', 'pause');
insert into Delivery_Man (id, name, Status) values (398, 'Jonathon', 'en cour');
insert into Delivery_Man (id, name, Status) values (399, 'Cori', 'en cour');
insert into Delivery_Man (id, name, Status) values (400, 'Eolanda', 'pause');
insert into Delivery_Man (id, name, Status) values (401, 'Gwenore', 'en cour');
insert into Delivery_Man (id, name, Status) values (402, 'Kim', 'pause');
insert into Delivery_Man (id, name, Status) values (403, 'Goldia', 'en cour');
insert into Delivery_Man (id, name, Status) values (404, 'Worthington', 'pause');
insert into Delivery_Man (id, name, Status) values (405, 'Judas', 'pause');
insert into Delivery_Man (id, name, Status) values (406, 'Agretha', 'pause');
insert into Delivery_Man (id, name, Status) values (407, 'Elwira', 'en cour');
insert into Delivery_Man (id, name, Status) values (408, 'Adara', 'finish');
insert into Delivery_Man (id, name, Status) values (409, 'Manuel', 'pause');
insert into Delivery_Man (id, name, Status) values (410, 'Shaun', 'pause');
insert into Delivery_Man (id, name, Status) values (411, 'Lin', 'finish');
insert into Delivery_Man (id, name, Status) values (412, 'Gretta', 'en cour');
insert into Delivery_Man (id, name, Status) values (413, 'Marie-ann', 'en cour');
insert into Delivery_Man (id, name, Status) values (414, 'Ada', 'finish');
insert into Delivery_Man (id, name, Status) values (415, 'Luise', 'pause');
insert into Delivery_Man (id, name, Status) values (416, 'Thayne', 'finish');
insert into Delivery_Man (id, name, Status) values (417, 'Brandi', 'pause');
insert into Delivery_Man (id, name, Status) values (418, 'Iorgo', 'en cour');
insert into Delivery_Man (id, name, Status) values (419, 'Lauraine', 'pause');
insert into Delivery_Man (id, name, Status) values (420, 'Leonerd', 'finish');
insert into Delivery_Man (id, name, Status) values (421, 'Beckie', 'en cour');
insert into Delivery_Man (id, name, Status) values (422, 'Wilmer', 'finish');
insert into Delivery_Man (id, name, Status) values (423, 'Ivor', 'en cour');
insert into Delivery_Man (id, name, Status) values (424, 'Mose', 'finish');
insert into Delivery_Man (id, name, Status) values (425, 'Basia', 'finish');
insert into Delivery_Man (id, name, Status) values (426, 'Essy', 'pause');
insert into Delivery_Man (id, name, Status) values (427, 'Wolfgang', 'en cour');
insert into Delivery_Man (id, name, Status) values (428, 'Iolanthe', 'en cour');
insert into Delivery_Man (id, name, Status) values (429, 'Garwood', 'finish');
insert into Delivery_Man (id, name, Status) values (430, 'Marinna', 'finish');
insert into Delivery_Man (id, name, Status) values (431, 'Lilith', 'pause');
insert into Delivery_Man (id, name, Status) values (432, 'Leandra', 'en cour');
insert into Delivery_Man (id, name, Status) values (433, 'Leshia', 'en cour');
insert into Delivery_Man (id, name, Status) values (434, 'Elena', 'pause');
insert into Delivery_Man (id, name, Status) values (435, 'Dante', 'finish');
insert into Delivery_Man (id, name, Status) values (436, 'Marni', 'pause');
insert into Delivery_Man (id, name, Status) values (437, 'Phebe', 'en cour');
insert into Delivery_Man (id, name, Status) values (438, 'Alexandros', 'en cour');
insert into Delivery_Man (id, name, Status) values (439, 'Sidonia', 'finish');
insert into Delivery_Man (id, name, Status) values (440, 'Donn', 'pause');
insert into Delivery_Man (id, name, Status) values (441, 'Shelden', 'pause');
insert into Delivery_Man (id, name, Status) values (442, 'Lilian', 'en cour');
insert into Delivery_Man (id, name, Status) values (443, 'Dave', 'finish');
insert into Delivery_Man (id, name, Status) values (444, 'Heidi', 'en cour');
insert into Delivery_Man (id, name, Status) values (445, 'Nichole', 'en cour');
insert into Delivery_Man (id, name, Status) values (446, 'Silas', 'finish');
insert into Delivery_Man (id, name, Status) values (447, 'Eberhard', 'pause');
insert into Delivery_Man (id, name, Status) values (448, 'Gamaliel', 'pause');
insert into Delivery_Man (id, name, Status) values (449, 'Roxana', 'pause');
insert into Delivery_Man (id, name, Status) values (450, 'Orbadiah', 'pause');
insert into Delivery_Man (id, name, Status) values (451, 'Clementia', 'en cour');
insert into Delivery_Man (id, name, Status) values (452, 'Carter', 'finish');
insert into Delivery_Man (id, name, Status) values (453, 'Melonie', 'en cour');
insert into Delivery_Man (id, name, Status) values (454, 'Em', 'pause');
insert into Delivery_Man (id, name, Status) values (455, 'Walsh', 'en cour');
insert into Delivery_Man (id, name, Status) values (456, 'Ethe', 'en cour');
insert into Delivery_Man (id, name, Status) values (457, 'Cyrillus', 'en cour');
insert into Delivery_Man (id, name, Status) values (458, 'Noach', 'en cour');
insert into Delivery_Man (id, name, Status) values (459, 'Flo', 'finish');
insert into Delivery_Man (id, name, Status) values (460, 'Waylan', 'en cour');
insert into Delivery_Man (id, name, Status) values (461, 'Ingaborg', 'en cour');
insert into Delivery_Man (id, name, Status) values (462, 'Leonanie', 'finish');
insert into Delivery_Man (id, name, Status) values (463, 'Giuditta', 'finish');
insert into Delivery_Man (id, name, Status) values (464, 'Karlene', 'pause');
insert into Delivery_Man (id, name, Status) values (465, 'Sterne', 'finish');
insert into Delivery_Man (id, name, Status) values (466, 'Ina', 'finish');
insert into Delivery_Man (id, name, Status) values (467, 'Irv', 'en cour');
insert into Delivery_Man (id, name, Status) values (468, 'Deni', 'finish');
insert into Delivery_Man (id, name, Status) values (469, 'Ernst', 'en cour');
insert into Delivery_Man (id, name, Status) values (470, 'Renaldo', 'pause');
insert into Delivery_Man (id, name, Status) values (471, 'Kristel', 'pause');
insert into Delivery_Man (id, name, Status) values (472, 'Pavia', 'pause');
insert into Delivery_Man (id, name, Status) values (473, 'Evy', 'finish');
insert into Delivery_Man (id, name, Status) values (474, 'Anestassia', 'finish');
insert into Delivery_Man (id, name, Status) values (475, 'Dix', 'pause');
insert into Delivery_Man (id, name, Status) values (476, 'Gabe', 'finish');
insert into Delivery_Man (id, name, Status) values (477, 'Alford', 'finish');
insert into Delivery_Man (id, name, Status) values (478, 'Dominga', 'pause');
insert into Delivery_Man (id, name, Status) values (479, 'Doll', 'en cour');
insert into Delivery_Man (id, name, Status) values (480, 'Valentin', 'finish');
insert into Delivery_Man (id, name, Status) values (481, 'Hasheem', 'finish');
insert into Delivery_Man (id, name, Status) values (482, 'Revkah', 'finish');
insert into Delivery_Man (id, name, Status) values (483, 'Filberte', 'en cour');
insert into Delivery_Man (id, name, Status) values (484, 'Freemon', 'finish');
insert into Delivery_Man (id, name, Status) values (485, 'Jerome', 'finish');
insert into Delivery_Man (id, name, Status) values (486, 'Celinka', 'en cour');
insert into Delivery_Man (id, name, Status) values (487, 'Paul', 'pause');
insert into Delivery_Man (id, name, Status) values (488, 'Clemmy', 'finish');
insert into Delivery_Man (id, name, Status) values (489, 'Euphemia', 'en cour');
insert into Delivery_Man (id, name, Status) values (490, 'Henri', 'finish');
insert into Delivery_Man (id, name, Status) values (491, 'Yance', 'pause');
insert into Delivery_Man (id, name, Status) values (492, 'Patrizia', 'finish');
insert into Delivery_Man (id, name, Status) values (493, 'Garrard', 'en cour');
insert into Delivery_Man (id, name, Status) values (494, 'Luke', 'finish');
insert into Delivery_Man (id, name, Status) values (495, 'Marabel', 'finish');
insert into Delivery_Man (id, name, Status) values (496, 'Rosabella', 'pause');
insert into Delivery_Man (id, name, Status) values (497, 'Lauree', 'finish');
insert into Delivery_Man (id, name, Status) values (498, 'Corilla', 'finish');
insert into Delivery_Man (id, name, Status) values (499, 'Marni', 'en cour');
insert into Delivery_Man (id, name, Status) values (500, 'Torrence', 'finish');
insert into Delivery_Man (id, name, Status) values (501, 'Kimmy', 'pause');
insert into Delivery_Man (id, name, Status) values (502, 'Vic', 'pause');
insert into Delivery_Man (id, name, Status) values (503, 'Rube', 'pause');
insert into Delivery_Man (id, name, Status) values (504, 'Elnore', 'pause');
insert into Delivery_Man (id, name, Status) values (505, 'Adham', 'en cour');
insert into Delivery_Man (id, name, Status) values (506, 'Luce', 'pause');
insert into Delivery_Man (id, name, Status) values (507, 'Shandy', 'finish');
insert into Delivery_Man (id, name, Status) values (508, 'Grayce', 'en cour');
insert into Delivery_Man (id, name, Status) values (509, 'Wake', 'finish');
insert into Delivery_Man (id, name, Status) values (510, 'Derry', 'en cour');
insert into Delivery_Man (id, name, Status) values (511, 'Burtie', 'en cour');
insert into Delivery_Man (id, name, Status) values (512, 'Peri', 'en cour');
insert into Delivery_Man (id, name, Status) values (513, 'Warner', 'en cour');
insert into Delivery_Man (id, name, Status) values (514, 'Noreen', 'finish');
insert into Delivery_Man (id, name, Status) values (515, 'Harlene', 'pause');
insert into Delivery_Man (id, name, Status) values (516, 'Sula', 'pause');
insert into Delivery_Man (id, name, Status) values (517, 'Kassandra', 'pause');
insert into Delivery_Man (id, name, Status) values (518, 'Brock', 'en cour');
insert into Delivery_Man (id, name, Status) values (519, 'Philipa', 'finish');
insert into Delivery_Man (id, name, Status) values (520, 'Lizzy', 'en cour');
insert into Delivery_Man (id, name, Status) values (521, 'Darrell', 'pause');
insert into Delivery_Man (id, name, Status) values (522, 'Graeme', 'finish');
insert into Delivery_Man (id, name, Status) values (523, 'Rochella', 'pause');
insert into Delivery_Man (id, name, Status) values (524, 'Prinz', 'pause');
insert into Delivery_Man (id, name, Status) values (525, 'Aliza', 'en cour');
insert into Delivery_Man (id, name, Status) values (526, 'Kalinda', 'en cour');
insert into Delivery_Man (id, name, Status) values (527, 'Garold', 'en cour');
insert into Delivery_Man (id, name, Status) values (528, 'Cathi', 'en cour');
insert into Delivery_Man (id, name, Status) values (529, 'Gerome', 'pause');
insert into Delivery_Man (id, name, Status) values (530, 'Pen', 'en cour');
insert into Delivery_Man (id, name, Status) values (531, 'Judi', 'finish');
insert into Delivery_Man (id, name, Status) values (532, 'Alex', 'en cour');
insert into Delivery_Man (id, name, Status) values (533, 'Teodorico', 'en cour');
insert into Delivery_Man (id, name, Status) values (534, 'Barb', 'en cour');
insert into Delivery_Man (id, name, Status) values (535, 'Patrick', 'pause');
insert into Delivery_Man (id, name, Status) values (536, 'Jobyna', 'en cour');
insert into Delivery_Man (id, name, Status) values (537, 'Dimitri', 'en cour');
insert into Delivery_Man (id, name, Status) values (538, 'Aveline', 'finish');
insert into Delivery_Man (id, name, Status) values (539, 'Rickie', 'en cour');
insert into Delivery_Man (id, name, Status) values (540, 'Annmarie', 'en cour');
insert into Delivery_Man (id, name, Status) values (541, 'Gilda', 'pause');
insert into Delivery_Man (id, name, Status) values (542, 'Benoit', 'en cour');
insert into Delivery_Man (id, name, Status) values (543, 'Harlan', 'en cour');
insert into Delivery_Man (id, name, Status) values (544, 'Zaneta', 'finish');
insert into Delivery_Man (id, name, Status) values (545, 'Rem', 'pause');
insert into Delivery_Man (id, name, Status) values (546, 'Jacquelin', 'pause');
insert into Delivery_Man (id, name, Status) values (547, 'Lorelle', 'en cour');
insert into Delivery_Man (id, name, Status) values (548, 'Delmar', 'en cour');
insert into Delivery_Man (id, name, Status) values (549, 'Delaney', 'finish');
insert into Delivery_Man (id, name, Status) values (550, 'Glenine', 'finish');
insert into Delivery_Man (id, name, Status) values (551, 'Trueman', 'en cour');
insert into Delivery_Man (id, name, Status) values (552, 'Jennifer', 'pause');
insert into Delivery_Man (id, name, Status) values (553, 'Hestia', 'pause');
insert into Delivery_Man (id, name, Status) values (554, 'Fancie', 'finish');
insert into Delivery_Man (id, name, Status) values (555, 'Alicea', 'finish');
insert into Delivery_Man (id, name, Status) values (556, 'Adriane', 'en cour');
insert into Delivery_Man (id, name, Status) values (557, 'Mavra', 'pause');
insert into Delivery_Man (id, name, Status) values (558, 'Webb', 'en cour');
insert into Delivery_Man (id, name, Status) values (559, 'Alfy', 'pause');
insert into Delivery_Man (id, name, Status) values (560, 'Andi', 'finish');
insert into Delivery_Man (id, name, Status) values (561, 'Vanni', 'pause');
insert into Delivery_Man (id, name, Status) values (562, 'Adena', 'pause');
insert into Delivery_Man (id, name, Status) values (563, 'Bradney', 'en cour');
insert into Delivery_Man (id, name, Status) values (564, 'Evy', 'en cour');
insert into Delivery_Man (id, name, Status) values (565, 'Yorke', 'en cour');
insert into Delivery_Man (id, name, Status) values (566, 'Kristofer', 'en cour');
insert into Delivery_Man (id, name, Status) values (567, 'Gaylene', 'pause');
insert into Delivery_Man (id, name, Status) values (568, 'Misha', 'en cour');
insert into Delivery_Man (id, name, Status) values (569, 'Jorrie', 'en cour');
insert into Delivery_Man (id, name, Status) values (570, 'Cassondra', 'finish');
insert into Delivery_Man (id, name, Status) values (571, 'Merwyn', 'pause');
insert into Delivery_Man (id, name, Status) values (572, 'Hillie', 'en cour');
insert into Delivery_Man (id, name, Status) values (573, 'Harmonie', 'finish');
insert into Delivery_Man (id, name, Status) values (574, 'Cully', 'finish');
insert into Delivery_Man (id, name, Status) values (575, 'Basil', 'finish');
insert into Delivery_Man (id, name, Status) values (576, 'Vi', 'en cour');
insert into Delivery_Man (id, name, Status) values (577, 'Madelyn', 'finish');
insert into Delivery_Man (id, name, Status) values (578, 'Enos', 'en cour');
insert into Delivery_Man (id, name, Status) values (579, 'Roman', 'pause');
insert into Delivery_Man (id, name, Status) values (580, 'Antonia', 'finish');
insert into Delivery_Man (id, name, Status) values (581, 'Dean', 'pause');
insert into Delivery_Man (id, name, Status) values (582, 'Hansiain', 'finish');
insert into Delivery_Man (id, name, Status) values (583, 'Bernadette', 'en cour');
insert into Delivery_Man (id, name, Status) values (584, 'Daryn', 'en cour');
insert into Delivery_Man (id, name, Status) values (585, 'Rudie', 'en cour');
insert into Delivery_Man (id, name, Status) values (586, 'Freddy', 'pause');
insert into Delivery_Man (id, name, Status) values (587, 'Merilee', 'en cour');
insert into Delivery_Man (id, name, Status) values (588, 'Burty', 'finish');
insert into Delivery_Man (id, name, Status) values (589, 'Zacharie', 'finish');
insert into Delivery_Man (id, name, Status) values (590, 'Sherm', 'pause');
insert into Delivery_Man (id, name, Status) values (591, 'Hyman', 'pause');
insert into Delivery_Man (id, name, Status) values (592, 'Hetty', 'en cour');
insert into Delivery_Man (id, name, Status) values (593, 'Tildi', 'en cour');
insert into Delivery_Man (id, name, Status) values (594, 'Merrili', 'finish');
insert into Delivery_Man (id, name, Status) values (595, 'Josephina', 'en cour');
insert into Delivery_Man (id, name, Status) values (596, 'Laurice', 'en cour');
insert into Delivery_Man (id, name, Status) values (597, 'Wernher', 'en cour');
insert into Delivery_Man (id, name, Status) values (598, 'Kitti', 'finish');
insert into Delivery_Man (id, name, Status) values (599, 'Dominik', 'en cour');
insert into Delivery_Man (id, name, Status) values (600, 'Sara', 'en cour');
insert into Delivery_Man (id, name, Status) values (601, 'Myer', 'pause');
insert into Delivery_Man (id, name, Status) values (602, 'Sukey', 'finish');
insert into Delivery_Man (id, name, Status) values (603, 'Dougy', 'pause');
insert into Delivery_Man (id, name, Status) values (604, 'Loretta', 'pause');
insert into Delivery_Man (id, name, Status) values (605, 'Francesca', 'pause');
insert into Delivery_Man (id, name, Status) values (606, 'Packston', 'finish');
insert into Delivery_Man (id, name, Status) values (607, 'Christos', 'en cour');
insert into Delivery_Man (id, name, Status) values (608, 'Shelly', 'en cour');
insert into Delivery_Man (id, name, Status) values (609, 'Ari', 'pause');
insert into Delivery_Man (id, name, Status) values (610, 'Tamqrah', 'finish');
insert into Delivery_Man (id, name, Status) values (611, 'Flynn', 'en cour');
insert into Delivery_Man (id, name, Status) values (612, 'Vilhelmina', 'pause');
insert into Delivery_Man (id, name, Status) values (613, 'Beitris', 'finish');
insert into Delivery_Man (id, name, Status) values (614, 'Gabbi', 'pause');
insert into Delivery_Man (id, name, Status) values (615, 'Archibold', 'pause');
insert into Delivery_Man (id, name, Status) values (616, 'Selby', 'pause');
insert into Delivery_Man (id, name, Status) values (617, 'Karine', 'pause');
insert into Delivery_Man (id, name, Status) values (618, 'Gasparo', 'en cour');
insert into Delivery_Man (id, name, Status) values (619, 'Claude', 'pause');
insert into Delivery_Man (id, name, Status) values (620, 'Morgana', 'en cour');
insert into Delivery_Man (id, name, Status) values (621, 'Thoma', 'pause');
insert into Delivery_Man (id, name, Status) values (622, 'Lamont', 'finish');
insert into Delivery_Man (id, name, Status) values (623, 'Aimil', 'en cour');
insert into Delivery_Man (id, name, Status) values (624, 'Jacob', 'finish');
insert into Delivery_Man (id, name, Status) values (625, 'Sada', 'finish');
insert into Delivery_Man (id, name, Status) values (626, 'Lutero', 'pause');
insert into Delivery_Man (id, name, Status) values (627, 'Andra', 'en cour');
insert into Delivery_Man (id, name, Status) values (628, 'Leonidas', 'finish');
insert into Delivery_Man (id, name, Status) values (629, 'Sabina', 'en cour');
insert into Delivery_Man (id, name, Status) values (630, 'Alexis', 'pause');
insert into Delivery_Man (id, name, Status) values (631, 'Cherry', 'en cour');
insert into Delivery_Man (id, name, Status) values (632, 'Sigfried', 'en cour');
insert into Delivery_Man (id, name, Status) values (633, 'Crissy', 'en cour');
insert into Delivery_Man (id, name, Status) values (634, 'Andra', 'finish');
insert into Delivery_Man (id, name, Status) values (635, 'Kerk', 'en cour');
insert into Delivery_Man (id, name, Status) values (636, 'Freddi', 'en cour');
insert into Delivery_Man (id, name, Status) values (637, 'Jenny', 'finish');
insert into Delivery_Man (id, name, Status) values (638, 'Terrence', 'pause');
insert into Delivery_Man (id, name, Status) values (639, 'Shani', 'pause');
insert into Delivery_Man (id, name, Status) values (640, 'Morganica', 'finish');
insert into Delivery_Man (id, name, Status) values (641, 'Mariam', 'finish');
insert into Delivery_Man (id, name, Status) values (642, 'Wilie', 'pause');
insert into Delivery_Man (id, name, Status) values (643, 'Corney', 'pause');
insert into Delivery_Man (id, name, Status) values (644, 'Edi', 'en cour');
insert into Delivery_Man (id, name, Status) values (645, 'Korney', 'pause');
insert into Delivery_Man (id, name, Status) values (646, 'Derward', 'en cour');
insert into Delivery_Man (id, name, Status) values (647, 'Toiboid', 'finish');
insert into Delivery_Man (id, name, Status) values (648, 'Timothea', 'en cour');
insert into Delivery_Man (id, name, Status) values (649, 'Aloin', 'finish');
insert into Delivery_Man (id, name, Status) values (650, 'Trudey', 'pause');
insert into Delivery_Man (id, name, Status) values (651, 'Johny', 'pause');
insert into Delivery_Man (id, name, Status) values (652, 'Nataline', 'en cour');
insert into Delivery_Man (id, name, Status) values (653, 'Bancroft', 'finish');
insert into Delivery_Man (id, name, Status) values (654, 'Aileen', 'pause');
insert into Delivery_Man (id, name, Status) values (655, 'Sonnnie', 'pause');
insert into Delivery_Man (id, name, Status) values (656, 'Hyacinthe', 'en cour');
insert into Delivery_Man (id, name, Status) values (657, 'Minda', 'finish');
insert into Delivery_Man (id, name, Status) values (658, 'Buckie', 'finish');
insert into Delivery_Man (id, name, Status) values (659, 'Caitlin', 'en cour');
insert into Delivery_Man (id, name, Status) values (660, 'Antoni', 'en cour');
insert into Delivery_Man (id, name, Status) values (661, 'Kore', 'pause');
insert into Delivery_Man (id, name, Status) values (662, 'Chic', 'en cour');
insert into Delivery_Man (id, name, Status) values (663, 'Conny', 'finish');
insert into Delivery_Man (id, name, Status) values (664, 'Miranda', 'pause');
insert into Delivery_Man (id, name, Status) values (665, 'Saudra', 'pause');
insert into Delivery_Man (id, name, Status) values (666, 'Felecia', 'en cour');
insert into Delivery_Man (id, name, Status) values (667, 'Tina', 'finish');
insert into Delivery_Man (id, name, Status) values (668, 'Salomo', 'finish');
insert into Delivery_Man (id, name, Status) values (669, 'Lennie', 'finish');
insert into Delivery_Man (id, name, Status) values (670, 'Jenine', 'pause');
insert into Delivery_Man (id, name, Status) values (671, 'Emmey', 'en cour');
insert into Delivery_Man (id, name, Status) values (672, 'Danyelle', 'finish');
insert into Delivery_Man (id, name, Status) values (673, 'Mathias', 'pause');
insert into Delivery_Man (id, name, Status) values (674, 'Dawn', 'finish');
insert into Delivery_Man (id, name, Status) values (675, 'Waring', 'pause');
insert into Delivery_Man (id, name, Status) values (676, 'Thornton', 'en cour');
insert into Delivery_Man (id, name, Status) values (677, 'Brandy', 'pause');
insert into Delivery_Man (id, name, Status) values (678, 'Janine', 'en cour');
insert into Delivery_Man (id, name, Status) values (679, 'Curcio', 'pause');
insert into Delivery_Man (id, name, Status) values (680, 'Lela', 'en cour');
insert into Delivery_Man (id, name, Status) values (681, 'Olivie', 'pause');
insert into Delivery_Man (id, name, Status) values (682, 'Georgetta', 'pause');
insert into Delivery_Man (id, name, Status) values (683, 'Mame', 'finish');
insert into Delivery_Man (id, name, Status) values (684, 'Webb', 'finish');
insert into Delivery_Man (id, name, Status) values (685, 'Wendall', 'en cour');
insert into Delivery_Man (id, name, Status) values (686, 'Frieda', 'en cour');
insert into Delivery_Man (id, name, Status) values (687, 'North', 'finish');
insert into Delivery_Man (id, name, Status) values (688, 'Rachael', 'en cour');
insert into Delivery_Man (id, name, Status) values (689, 'Jecho', 'en cour');
insert into Delivery_Man (id, name, Status) values (690, 'Jayne', 'finish');
insert into Delivery_Man (id, name, Status) values (691, 'Ethelda', 'finish');
insert into Delivery_Man (id, name, Status) values (692, 'Taddeusz', 'en cour');
insert into Delivery_Man (id, name, Status) values (693, 'Thomasa', 'pause');
insert into Delivery_Man (id, name, Status) values (694, 'Lenette', 'pause');
insert into Delivery_Man (id, name, Status) values (695, 'Catherina', 'pause');
insert into Delivery_Man (id, name, Status) values (696, 'Jeralee', 'pause');
insert into Delivery_Man (id, name, Status) values (697, 'Sukey', 'pause');
insert into Delivery_Man (id, name, Status) values (698, 'Malia', 'en cour');
insert into Delivery_Man (id, name, Status) values (699, 'Rosalie', 'finish');
insert into Delivery_Man (id, name, Status) values (700, 'Pascale', 'en cour');
insert into Delivery_Man (id, name, Status) values (701, 'Rosalinde', 'finish');
insert into Delivery_Man (id, name, Status) values (702, 'Doug', 'finish');
insert into Delivery_Man (id, name, Status) values (703, 'Biddy', 'en cour');
insert into Delivery_Man (id, name, Status) values (704, 'Randi', 'pause');
insert into Delivery_Man (id, name, Status) values (705, 'Tildy', 'en cour');
insert into Delivery_Man (id, name, Status) values (706, 'Celinda', 'finish');
insert into Delivery_Man (id, name, Status) values (707, 'Killy', 'en cour');
insert into Delivery_Man (id, name, Status) values (708, 'Dudley', 'finish');
insert into Delivery_Man (id, name, Status) values (709, 'Annemarie', 'en cour');
insert into Delivery_Man (id, name, Status) values (710, 'Caro', 'pause');
insert into Delivery_Man (id, name, Status) values (711, 'Denise', 'en cour');
insert into Delivery_Man (id, name, Status) values (712, 'Anton', 'finish');
insert into Delivery_Man (id, name, Status) values (713, 'Dex', 'en cour');
insert into Delivery_Man (id, name, Status) values (714, 'Chane', 'en cour');
insert into Delivery_Man (id, name, Status) values (715, 'Susanne', 'finish');
insert into Delivery_Man (id, name, Status) values (716, 'Ingaberg', 'pause');
insert into Delivery_Man (id, name, Status) values (717, 'Liam', 'en cour');
insert into Delivery_Man (id, name, Status) values (718, 'Gorden', 'pause');
insert into Delivery_Man (id, name, Status) values (719, 'Elisabet', 'finish');
insert into Delivery_Man (id, name, Status) values (720, 'Remington', 'en cour');
insert into Delivery_Man (id, name, Status) values (721, 'Twila', 'en cour');
insert into Delivery_Man (id, name, Status) values (722, 'Stirling', 'finish');
insert into Delivery_Man (id, name, Status) values (723, 'Molly', 'pause');
insert into Delivery_Man (id, name, Status) values (724, 'Danielle', 'pause');
insert into Delivery_Man (id, name, Status) values (725, 'Karlyn', 'en cour');
insert into Delivery_Man (id, name, Status) values (726, 'Dyan', 'pause');
insert into Delivery_Man (id, name, Status) values (727, 'Vinni', 'finish');
insert into Delivery_Man (id, name, Status) values (728, 'Paule', 'finish');
insert into Delivery_Man (id, name, Status) values (729, 'Waneta', 'finish');
insert into Delivery_Man (id, name, Status) values (730, 'Marissa', 'en cour');
insert into Delivery_Man (id, name, Status) values (731, 'Artus', 'pause');
insert into Delivery_Man (id, name, Status) values (732, 'Harwell', 'finish');
insert into Delivery_Man (id, name, Status) values (733, 'Marsiella', 'pause');
insert into Delivery_Man (id, name, Status) values (734, 'Eloisa', 'pause');
insert into Delivery_Man (id, name, Status) values (735, 'Micky', 'pause');
insert into Delivery_Man (id, name, Status) values (736, 'Tristam', 'pause');
insert into Delivery_Man (id, name, Status) values (737, 'Cherri', 'en cour');
insert into Delivery_Man (id, name, Status) values (738, 'Bryn', 'pause');
insert into Delivery_Man (id, name, Status) values (739, 'Horst', 'finish');
insert into Delivery_Man (id, name, Status) values (740, 'Dudley', 'pause');
insert into Delivery_Man (id, name, Status) values (741, 'Stephan', 'en cour');
insert into Delivery_Man (id, name, Status) values (742, 'Myrle', 'pause');
insert into Delivery_Man (id, name, Status) values (743, 'Lisha', 'en cour');
insert into Delivery_Man (id, name, Status) values (744, 'Dix', 'finish');
insert into Delivery_Man (id, name, Status) values (745, 'Alastair', 'pause');
insert into Delivery_Man (id, name, Status) values (746, 'Marrissa', 'finish');
insert into Delivery_Man (id, name, Status) values (747, 'Marlo', 'en cour');
insert into Delivery_Man (id, name, Status) values (748, 'Celinda', 'pause');
insert into Delivery_Man (id, name, Status) values (749, 'Aurel', 'en cour');
insert into Delivery_Man (id, name, Status) values (750, 'Maison', 'finish');
insert into Delivery_Man (id, name, Status) values (751, 'Darlene', 'pause');
insert into Delivery_Man (id, name, Status) values (752, 'Leone', 'en cour');
insert into Delivery_Man (id, name, Status) values (753, 'Ferdinanda', 'pause');
insert into Delivery_Man (id, name, Status) values (754, 'Valery', 'pause');
insert into Delivery_Man (id, name, Status) values (755, 'Locke', 'finish');
insert into Delivery_Man (id, name, Status) values (756, 'Jeanette', 'finish');
insert into Delivery_Man (id, name, Status) values (757, 'Ethelda', 'en cour');
insert into Delivery_Man (id, name, Status) values (758, 'Care', 'finish');
insert into Delivery_Man (id, name, Status) values (759, 'Ramsey', 'en cour');
insert into Delivery_Man (id, name, Status) values (760, 'Everett', 'pause');
insert into Delivery_Man (id, name, Status) values (761, 'Candace', 'pause');
insert into Delivery_Man (id, name, Status) values (762, 'Sandro', 'finish');
insert into Delivery_Man (id, name, Status) values (763, 'Wandis', 'en cour');
insert into Delivery_Man (id, name, Status) values (764, 'Willie', 'pause');
insert into Delivery_Man (id, name, Status) values (765, 'Dyane', 'en cour');
insert into Delivery_Man (id, name, Status) values (766, 'Briana', 'finish');
insert into Delivery_Man (id, name, Status) values (767, 'Min', 'finish');
insert into Delivery_Man (id, name, Status) values (768, 'Benedikt', 'finish');
insert into Delivery_Man (id, name, Status) values (769, 'Delmore', 'finish');
insert into Delivery_Man (id, name, Status) values (770, 'Natassia', 'finish');
insert into Delivery_Man (id, name, Status) values (771, 'Goran', 'pause');
insert into Delivery_Man (id, name, Status) values (772, 'Karilynn', 'en cour');
insert into Delivery_Man (id, name, Status) values (773, 'Missy', 'en cour');
insert into Delivery_Man (id, name, Status) values (774, 'Rozanna', 'finish');
insert into Delivery_Man (id, name, Status) values (775, 'Dulcine', 'finish');
insert into Delivery_Man (id, name, Status) values (776, 'Garrick', 'finish');
insert into Delivery_Man (id, name, Status) values (777, 'Garek', 'en cour');
insert into Delivery_Man (id, name, Status) values (778, 'Mattie', 'finish');
insert into Delivery_Man (id, name, Status) values (779, 'Morgen', 'en cour');
insert into Delivery_Man (id, name, Status) values (780, 'Marni', 'pause');
insert into Delivery_Man (id, name, Status) values (781, 'Thadeus', 'pause');
insert into Delivery_Man (id, name, Status) values (782, 'Mallory', 'finish');
insert into Delivery_Man (id, name, Status) values (783, 'Carl', 'finish');
insert into Delivery_Man (id, name, Status) values (784, 'Pris', 'en cour');
insert into Delivery_Man (id, name, Status) values (785, 'Leia', 'en cour');
insert into Delivery_Man (id, name, Status) values (786, 'Tiffany', 'pause');
insert into Delivery_Man (id, name, Status) values (787, 'Juieta', 'finish');
insert into Delivery_Man (id, name, Status) values (788, 'Rosella', 'pause');
insert into Delivery_Man (id, name, Status) values (789, 'Stafani', 'pause');
insert into Delivery_Man (id, name, Status) values (790, 'Genovera', 'en cour');
insert into Delivery_Man (id, name, Status) values (791, 'Issy', 'en cour');
insert into Delivery_Man (id, name, Status) values (792, 'Loella', 'en cour');
insert into Delivery_Man (id, name, Status) values (793, 'Rosamond', 'finish');
insert into Delivery_Man (id, name, Status) values (794, 'Meredeth', 'en cour');
insert into Delivery_Man (id, name, Status) values (795, 'Tadeo', 'finish');
insert into Delivery_Man (id, name, Status) values (796, 'Ardis', 'pause');
insert into Delivery_Man (id, name, Status) values (797, 'Lyndsie', 'finish');
insert into Delivery_Man (id, name, Status) values (798, 'Keene', 'pause');
insert into Delivery_Man (id, name, Status) values (799, 'Fulvia', 'en cour');
insert into Delivery_Man (id, name, Status) values (800, 'Randal', 'en cour');
insert into Delivery_Man (id, name, Status) values (801, 'Nadia', 'en cour');
insert into Delivery_Man (id, name, Status) values (802, 'Codi', 'pause');
insert into Delivery_Man (id, name, Status) values (803, 'Marcy', 'en cour');
insert into Delivery_Man (id, name, Status) values (804, 'Maurene', 'pause');
insert into Delivery_Man (id, name, Status) values (805, 'Phip', 'en cour');
insert into Delivery_Man (id, name, Status) values (806, 'Reinwald', 'en cour');
insert into Delivery_Man (id, name, Status) values (807, 'Yorke', 'en cour');
insert into Delivery_Man (id, name, Status) values (808, 'Cinnamon', 'finish');
insert into Delivery_Man (id, name, Status) values (809, 'Russell', 'en cour');
insert into Delivery_Man (id, name, Status) values (810, 'Alfreda', 'finish');
insert into Delivery_Man (id, name, Status) values (811, 'Darci', 'pause');
insert into Delivery_Man (id, name, Status) values (812, 'Tab', 'pause');
insert into Delivery_Man (id, name, Status) values (813, 'Ruddie', 'en cour');
insert into Delivery_Man (id, name, Status) values (814, 'Viviana', 'en cour');
insert into Delivery_Man (id, name, Status) values (815, 'Zerk', 'finish');
insert into Delivery_Man (id, name, Status) values (816, 'Bertha', 'en cour');
insert into Delivery_Man (id, name, Status) values (817, 'Angelique', 'pause');
insert into Delivery_Man (id, name, Status) values (818, 'Rosco', 'en cour');
insert into Delivery_Man (id, name, Status) values (819, 'Joela', 'pause');
insert into Delivery_Man (id, name, Status) values (820, 'Von', 'en cour');
insert into Delivery_Man (id, name, Status) values (821, 'Jinny', 'finish');
insert into Delivery_Man (id, name, Status) values (822, 'Gwenni', 'finish');
insert into Delivery_Man (id, name, Status) values (823, 'Neal', 'pause');
insert into Delivery_Man (id, name, Status) values (824, 'Bran', 'finish');
insert into Delivery_Man (id, name, Status) values (825, 'Georgianne', 'finish');
insert into Delivery_Man (id, name, Status) values (826, 'Stafford', 'en cour');
insert into Delivery_Man (id, name, Status) values (827, 'Muhammad', 'finish');
insert into Delivery_Man (id, name, Status) values (828, 'Oneida', 'finish');
insert into Delivery_Man (id, name, Status) values (829, 'Oliy', 'finish');
insert into Delivery_Man (id, name, Status) values (830, 'Fernando', 'finish');
insert into Delivery_Man (id, name, Status) values (831, 'Wilhelm', 'en cour');
insert into Delivery_Man (id, name, Status) values (832, 'Jerry', 'en cour');
insert into Delivery_Man (id, name, Status) values (833, 'Mose', 'pause');
insert into Delivery_Man (id, name, Status) values (834, 'Trevor', 'en cour');
insert into Delivery_Man (id, name, Status) values (835, 'Luke', 'finish');
insert into Delivery_Man (id, name, Status) values (836, 'Marilyn', 'pause');
insert into Delivery_Man (id, name, Status) values (837, 'Nelle', 'en cour');
insert into Delivery_Man (id, name, Status) values (838, 'Doralin', 'pause');
insert into Delivery_Man (id, name, Status) values (839, 'Viviene', 'pause');
insert into Delivery_Man (id, name, Status) values (840, 'Ricardo', 'pause');
insert into Delivery_Man (id, name, Status) values (841, 'Halie', 'finish');
insert into Delivery_Man (id, name, Status) values (842, 'Stan', 'finish');
insert into Delivery_Man (id, name, Status) values (843, 'Sterling', 'pause');
insert into Delivery_Man (id, name, Status) values (844, 'Ros', 'finish');
insert into Delivery_Man (id, name, Status) values (845, 'Anastasia', 'pause');
insert into Delivery_Man (id, name, Status) values (846, 'Marcella', 'en cour');
insert into Delivery_Man (id, name, Status) values (847, 'Nomi', 'en cour');
insert into Delivery_Man (id, name, Status) values (848, 'Violette', 'pause');
insert into Delivery_Man (id, name, Status) values (849, 'Sutherland', 'finish');
insert into Delivery_Man (id, name, Status) values (850, 'Alfons', 'finish');
insert into Delivery_Man (id, name, Status) values (851, 'Willi', 'finish');
insert into Delivery_Man (id, name, Status) values (852, 'Matty', 'en cour');
insert into Delivery_Man (id, name, Status) values (853, 'Micheline', 'finish');
insert into Delivery_Man (id, name, Status) values (854, 'Philipa', 'pause');
insert into Delivery_Man (id, name, Status) values (855, 'Ruthi', 'finish');
insert into Delivery_Man (id, name, Status) values (856, 'Mathew', 'en cour');
insert into Delivery_Man (id, name, Status) values (857, 'Myrtie', 'finish');
insert into Delivery_Man (id, name, Status) values (858, 'Leicester', 'en cour');
insert into Delivery_Man (id, name, Status) values (859, 'Caron', 'en cour');
insert into Delivery_Man (id, name, Status) values (860, 'Ann', 'finish');
insert into Delivery_Man (id, name, Status) values (861, 'Elysha', 'en cour');
insert into Delivery_Man (id, name, Status) values (862, 'Tracy', 'en cour');
insert into Delivery_Man (id, name, Status) values (863, 'Tandie', 'en cour');
insert into Delivery_Man (id, name, Status) values (864, 'Wadsworth', 'en cour');
insert into Delivery_Man (id, name, Status) values (865, 'Mariejeanne', 'finish');
insert into Delivery_Man (id, name, Status) values (866, 'Bernice', 'finish');
insert into Delivery_Man (id, name, Status) values (867, 'Robbie', 'en cour');
insert into Delivery_Man (id, name, Status) values (868, 'Johann', 'en cour');
insert into Delivery_Man (id, name, Status) values (869, 'Ruggiero', 'finish');
insert into Delivery_Man (id, name, Status) values (870, 'Lauralee', 'pause');
insert into Delivery_Man (id, name, Status) values (871, 'Bondie', 'pause');
insert into Delivery_Man (id, name, Status) values (872, 'Percival', 'pause');
insert into Delivery_Man (id, name, Status) values (873, 'Rod', 'en cour');
insert into Delivery_Man (id, name, Status) values (874, 'Wilt', 'pause');
insert into Delivery_Man (id, name, Status) values (875, 'Loy', 'pause');
insert into Delivery_Man (id, name, Status) values (876, 'Tudor', 'pause');
insert into Delivery_Man (id, name, Status) values (877, 'Leroi', 'finish');
insert into Delivery_Man (id, name, Status) values (878, 'Emma', 'finish');
insert into Delivery_Man (id, name, Status) values (879, 'Hertha', 'finish');
insert into Delivery_Man (id, name, Status) values (880, 'Malina', 'en cour');
insert into Delivery_Man (id, name, Status) values (881, 'Madlen', 'pause');
insert into Delivery_Man (id, name, Status) values (882, 'Nikki', 'pause');
insert into Delivery_Man (id, name, Status) values (883, 'Frazer', 'pause');
insert into Delivery_Man (id, name, Status) values (884, 'Emili', 'pause');
insert into Delivery_Man (id, name, Status) values (885, 'Moreen', 'en cour');
insert into Delivery_Man (id, name, Status) values (886, 'Karyn', 'finish');
insert into Delivery_Man (id, name, Status) values (887, 'Wrennie', 'en cour');
insert into Delivery_Man (id, name, Status) values (888, 'Madlen', 'pause');
insert into Delivery_Man (id, name, Status) values (889, 'Lynde', 'finish');
insert into Delivery_Man (id, name, Status) values (890, 'Sydel', 'en cour');
insert into Delivery_Man (id, name, Status) values (891, 'Aldus', 'finish');
insert into Delivery_Man (id, name, Status) values (892, 'Hadleigh', 'finish');
insert into Delivery_Man (id, name, Status) values (893, 'Bridgette', 'finish');
insert into Delivery_Man (id, name, Status) values (894, 'Freedman', 'en cour');
insert into Delivery_Man (id, name, Status) values (895, 'Bridgette', 'pause');
insert into Delivery_Man (id, name, Status) values (896, 'Ashely', 'pause');
insert into Delivery_Man (id, name, Status) values (897, 'Sascha', 'finish');
insert into Delivery_Man (id, name, Status) values (898, 'Brianna', 'en cour');
insert into Delivery_Man (id, name, Status) values (899, 'Yoshi', 'finish');
insert into Delivery_Man (id, name, Status) values (900, 'Shannon', 'en cour');
insert into Delivery_Man (id, name, Status) values (901, 'Opalina', 'pause');
insert into Delivery_Man (id, name, Status) values (902, 'Alice', 'finish');
insert into Delivery_Man (id, name, Status) values (903, 'Tuckie', 'en cour');
insert into Delivery_Man (id, name, Status) values (904, 'Mikol', 'finish');
insert into Delivery_Man (id, name, Status) values (905, 'Hubie', 'finish');
insert into Delivery_Man (id, name, Status) values (906, 'Deirdre', 'finish');
insert into Delivery_Man (id, name, Status) values (907, 'Perle', 'finish');
insert into Delivery_Man (id, name, Status) values (908, 'Camille', 'finish');
insert into Delivery_Man (id, name, Status) values (909, 'Carie', 'en cour');
insert into Delivery_Man (id, name, Status) values (910, 'Mehetabel', 'pause');
insert into Delivery_Man (id, name, Status) values (911, 'Fredelia', 'finish');
insert into Delivery_Man (id, name, Status) values (912, 'Keefer', 'en cour');
insert into Delivery_Man (id, name, Status) values (913, 'Grete', 'finish');
insert into Delivery_Man (id, name, Status) values (914, 'Olin', 'finish');
insert into Delivery_Man (id, name, Status) values (915, 'Maddie', 'finish');
insert into Delivery_Man (id, name, Status) values (916, 'Hakim', 'pause');
insert into Delivery_Man (id, name, Status) values (917, 'Rubia', 'pause');
insert into Delivery_Man (id, name, Status) values (918, 'Levin', 'en cour');
insert into Delivery_Man (id, name, Status) values (919, 'Waiter', 'en cour');
insert into Delivery_Man (id, name, Status) values (920, 'Melisenda', 'pause');
insert into Delivery_Man (id, name, Status) values (921, 'Tybalt', 'en cour');
insert into Delivery_Man (id, name, Status) values (922, 'Roze', 'finish');
insert into Delivery_Man (id, name, Status) values (923, 'Halsy', 'finish');
insert into Delivery_Man (id, name, Status) values (924, 'Berkeley', 'finish');
insert into Delivery_Man (id, name, Status) values (925, 'Emmalynne', 'pause');
insert into Delivery_Man (id, name, Status) values (926, 'Karel', 'en cour');
insert into Delivery_Man (id, name, Status) values (927, 'Ignacio', 'pause');
insert into Delivery_Man (id, name, Status) values (928, 'Tommy', 'pause');
insert into Delivery_Man (id, name, Status) values (929, 'Karlen', 'pause');
insert into Delivery_Man (id, name, Status) values (930, 'Holli', 'pause');
insert into Delivery_Man (id, name, Status) values (931, 'Sigfrid', 'en cour');
insert into Delivery_Man (id, name, Status) values (932, 'Rhea', 'en cour');
insert into Delivery_Man (id, name, Status) values (933, 'Virgilio', 'finish');
insert into Delivery_Man (id, name, Status) values (934, 'Ame', 'pause');
insert into Delivery_Man (id, name, Status) values (935, 'Tiler', 'en cour');
insert into Delivery_Man (id, name, Status) values (936, 'Alvira', 'pause');
insert into Delivery_Man (id, name, Status) values (937, 'Wendall', 'en cour');
insert into Delivery_Man (id, name, Status) values (938, 'Lauren', 'finish');
insert into Delivery_Man (id, name, Status) values (939, 'Sonni', 'en cour');
insert into Delivery_Man (id, name, Status) values (940, 'Ealasaid', 'pause');
insert into Delivery_Man (id, name, Status) values (941, 'Devondra', 'en cour');
insert into Delivery_Man (id, name, Status) values (942, 'Valentino', 'en cour');
insert into Delivery_Man (id, name, Status) values (943, 'Arabelle', 'pause');
insert into Delivery_Man (id, name, Status) values (944, 'Emlen', 'finish');
insert into Delivery_Man (id, name, Status) values (945, 'Hollie', 'finish');
insert into Delivery_Man (id, name, Status) values (946, 'Neille', 'finish');
insert into Delivery_Man (id, name, Status) values (947, 'Enrico', 'pause');
insert into Delivery_Man (id, name, Status) values (948, 'Quint', 'finish');
insert into Delivery_Man (id, name, Status) values (949, 'Catherina', 'en cour');
insert into Delivery_Man (id, name, Status) values (950, 'Gregorio', 'finish');
insert into Delivery_Man (id, name, Status) values (951, 'Nikita', 'finish');
insert into Delivery_Man (id, name, Status) values (952, 'Hadley', 'finish');
insert into Delivery_Man (id, name, Status) values (953, 'Kathy', 'en cour');
insert into Delivery_Man (id, name, Status) values (954, 'Arlee', 'finish');
insert into Delivery_Man (id, name, Status) values (955, 'Giordano', 'pause');
insert into Delivery_Man (id, name, Status) values (956, 'Kleon', 'pause');
insert into Delivery_Man (id, name, Status) values (957, 'Derry', 'pause');
insert into Delivery_Man (id, name, Status) values (958, 'Philippa', 'finish');
insert into Delivery_Man (id, name, Status) values (959, 'Madelene', 'finish');
insert into Delivery_Man (id, name, Status) values (960, 'Timofei', 'pause');
insert into Delivery_Man (id, name, Status) values (961, 'Jenda', 'pause');
insert into Delivery_Man (id, name, Status) values (962, 'Virgie', 'finish');
insert into Delivery_Man (id, name, Status) values (963, 'Wes', 'en cour');
insert into Delivery_Man (id, name, Status) values (964, 'Kissiah', 'en cour');
insert into Delivery_Man (id, name, Status) values (965, 'Theresita', 'finish');
insert into Delivery_Man (id, name, Status) values (966, 'Abe', 'finish');
insert into Delivery_Man (id, name, Status) values (967, 'Iseabal', 'en cour');
insert into Delivery_Man (id, name, Status) values (968, 'Jerrome', 'pause');
insert into Delivery_Man (id, name, Status) values (969, 'Addie', 'en cour');
insert into Delivery_Man (id, name, Status) values (970, 'Ali', 'pause');
insert into Delivery_Man (id, name, Status) values (971, 'Florinda', 'finish');
insert into Delivery_Man (id, name, Status) values (972, 'Ogdan', 'finish');
insert into Delivery_Man (id, name, Status) values (973, 'Ephraim', 'finish');
insert into Delivery_Man (id, name, Status) values (974, 'Ranique', 'pause');
insert into Delivery_Man (id, name, Status) values (975, 'Zarla', 'pause');
insert into Delivery_Man (id, name, Status) values (976, 'Bibbie', 'finish');
insert into Delivery_Man (id, name, Status) values (977, 'Georgine', 'en cour');
insert into Delivery_Man (id, name, Status) values (978, 'Ludwig', 'finish');
insert into Delivery_Man (id, name, Status) values (979, 'Brnaba', 'pause');
insert into Delivery_Man (id, name, Status) values (980, 'Aggie', 'finish');
insert into Delivery_Man (id, name, Status) values (981, 'Lorna', 'pause');
insert into Delivery_Man (id, name, Status) values (982, 'Saxon', 'finish');
insert into Delivery_Man (id, name, Status) values (983, 'Phyllys', 'pause');
insert into Delivery_Man (id, name, Status) values (984, 'Glynnis', 'pause');
insert into Delivery_Man (id, name, Status) values (985, 'Murial', 'finish');
insert into Delivery_Man (id, name, Status) values (986, 'Nollie', 'finish');
insert into Delivery_Man (id, name, Status) values (987, 'Jeramey', 'finish');
insert into Delivery_Man (id, name, Status) values (988, 'Durante', 'pause');
insert into Delivery_Man (id, name, Status) values (989, 'Everett', 'pause');
insert into Delivery_Man (id, name, Status) values (990, 'Reuben', 'en cour');
insert into Delivery_Man (id, name, Status) values (991, 'Myca', 'en cour');
insert into Delivery_Man (id, name, Status) values (992, 'Hastie', 'pause');
insert into Delivery_Man (id, name, Status) values (993, 'Marget', 'en cour');
insert into Delivery_Man (id, name, Status) values (994, 'Towney', 'finish');
insert into Delivery_Man (id, name, Status) values (995, 'Cate', 'en cour');
insert into Delivery_Man (id, name, Status) values (996, 'Baryram', 'en cour');
insert into Delivery_Man (id, name, Status) values (997, 'Bert', 'finish');
insert into Delivery_Man (id, name, Status) values (998, 'Wilhelm', 'pause');
insert into Delivery_Man (id, name, Status) values (999, 'Jolynn', 'pause');
insert into Delivery_Man (id, name, Status) values (1000, 'Glynn', 'pause');
